version: '3'

tasks:
  default:
    cmds:
      - task -l --sort none
  install:
    cmds:
      - task nvim bun volta
  nvim:
    cmds:
      - curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
      - tar -C $HOME/.config/nvim/bin -xzf nvim-linux64.tar.gz
      - rm nvim-linux64.tar.gz
      - echo 'export PATH="$HOME/.config/nvim/bin:$PATH"' >> $HOME/.bashrc
      - bash
  bun:
    cmds:
      - curl -fsSL https://bun.sh/install
      - bash
      - bun add --global @johnnymorganz/stylua-bin
      - bun add --global @fsouza/prettierd
      - bun add --global @tailwindcss/language-server
      - bun add --global typescript typescript-language-server
      - bun add --global wsl-open
  volta:
    cmds:
      - curl https://get.volta.sh
      - bash
      - volta install node
